---
# Project information
site_name: MkDocs Material Meta and tag index issue demo

theme:
  name: material

nav:
  - First tag: first-tag/index.md
  - Second tag: second-tag/index.md
  - Third tag: index.md
  - Tags index: tags.md

plugins:
  # it works when you have the meta plugin here
  # uncomment the following `meta: {}` line
  # and the tag index pages will display all pages
  # with tags even if the tags are set from the meta file
#  meta: {}
  # tags plugin config has to be after the meta for tag index to work with meta defined tags
  tags:
    tags_file: tags.md
